[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
evm_version = "cancun"
verbosity = 2
solc = "0.8.27"

[rpc_endpoints]
local = "http://localhost:8545"
upside = "https://${UPSIDE_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }

# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# https://book.getfoundry.sh/config/
# https://github.com/juanfranblanco/vscode-solidity?tab=readme-ov-file

[fmt]
sort_imports = true